version: '3.3'

services:
  app:
    image: python:3.11.2
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - backend
    command: bash -c "cd app
                      && pip install -r requirements.txt
                      && python manage.py makemigrations
                      && python manage.py migrate
                      && make start-server"

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgres/data
    networks:
      - backend
    ports:
      - 5432:5432


networks:
  backend: